FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git

RUN git clone https://github.com/kuroko-lang/kuroko
WORKDIR /kuroko
RUN make -j8
RUN make install

COPY . /repo
WORKDIR /repo
ENV DESTDIR=/install
RUN make -j8
RUN make install

FROM ubuntu:22.04 as package
COPY --from=builder /repo /repo
